


mikeio:
    database:
        url: jdbc:mysql://localhost:3306/heroes
        username: root
        password:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        hikari:
            dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
            pool-name: MikeIOPool
    hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
        format_sql: true


server:
  porT: 9000
  error:
      whitelabel:
          enabled: false
  context-path: /tipodecambio/

# Templates reloading during development
spring:
    profiles:
        active: #dev
    thymeleaf:
        cache: false
    resources:
        cache-period: 0

#        static-locations: /static/

#
#springfox:
#  documentation:
#   swagger:
#    v2:
#      path:

